services:
  tempo-init:
    image: busybox
    command: sh -c "chmod -R 777 /tmp/tempo"
    volumes:
      - tempo-data:/tmp/tempo

  # Tempo for trace storage
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
#      - "${OTLP_GRPC_PORT:-4317}:4317"  # OTLP gRPC receiver  # Disable when using Tempo directly
#      - "${OTLP_HTTP_PORT:-4318}:4318"  # OTLP HTTP receiver  # Disable when using Tempo directly
      - "${TEMPO_HTTP_PORT:-3200}:3200"  # Tempo HTTP (for Grafana)
      - "${JAEGER_INGEST_PORT:-14268}:14268"  # Jaeger ingest
    networks:
      - super_network

volumes:
  tempo-data:

networks:
  super_network:
    external: true
