name: Manual SSH Trigger Gamma

on:
  workflow_dispatch:
    inputs:
      TEMPO_HTTP_PORT:
        description: 'TEMPO_HTTP_PORT'
        required: true
        default: '3200'
        type: string
      JAEGER_INGEST_PORT:
        description: 'JAEGER_INGEST_PORT'
        required: true
        default: '14268'
        type: string
      command:
        description: 'Choose a command to run'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - stop
          - stop_and_deploy
          - purge
          - purge_and_deploy

jobs:
  copy-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA_GITHUB_MALAGACJ }}
          script: mkdir -p gha_deployments/tempo/manual

      - name: Copy artifact files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA_GITHUB_MALAGACJ }}
          source: "docker-compose.yaml tempo.yaml"
            #          target: ""
