name: Manual SSH Trigger

on:
  workflow_dispatch:
    inputs:
      TEMPO_HTTP_PORT:
        description: 'TEMPO_HTTP_PORT'
        required: true
        default: '3200'
        type: string
      JAEGER_INGEST_PORT:
        description: 'JAEGER_INGEST_PORT'
        required: true
        default: '14268'
        type: string
      command:
        description: 'Choose a command to run'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - stop
          - stop_and_deploy
          - purge
          - purge_and_deploy

jobs:
  call-copy_to_server:
    uses: malagacj/shared-actions/.github/workflows/reusable-build.yml@main
    secrets:
      ID_RSA_GITHUB_MALAGACJ: ${{ secrets.ID_RSA_GITHUB_MALAGACJ }}
      SERVER_NAME: ${{ secrets.SERVER_NAME }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      - name: Checkout code
